---
- name: Configure the server, Download the files from Github
  hosts: database
  vars:
    ansible_become_pass: "password"
    mysql_root_password: "123"
    mysql_db_name: "remote"
    mysql_user: "sasha"
    mysql_user_password: "123"
    sql_file_path: "/usr/games/web/remote-med.sql"  # Шлях до SQL-файлу
    mysql_bind_address: "0.0.0.0"  # Дозволяє підключення з інших IP-адрес

  tasks:
    - name: 0. Check the connection
      ping:

    - name: 1. Ensure the directory /var/lib/apt exists
      become: true
      file:
        path: "/var/lib/apt"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: 2. Ensure the directory /var/lib/apt/lists exists
      become: true
      file:
        path: "/var/lib/apt/lists"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: 3. Ensure the directory /var/lib/apt/lists/partial exists
      become: true
      file:
        path: "/var/lib/apt/lists/partial"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: 4. Update Ubuntu
      become: true
      shell: apt-get update

    - name: 5. Install MySQL and create a database
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-client
        - mysql-server

    - name: 6. Install python3-mysqldb
      become: true
      apt:
        name: python3-mysqldb
        state: present

    - name: 7. Ensure MySQL service is running
      become: true
      service:
        name: mysql
        state: started
        enabled: yes

    - name: 8. Create MySQL database
      become: true
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: present
      vars:
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: 9. Create MySQL user
      become: true
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_user_password }}"
        priv: "{{ mysql_db_name }}.*:ALL"
        host: "%"
        state: present
      vars:
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: 10. Install Git on the web server
      become: true
      apt: name=git state=latest

    - name: 11. Clone a public repository
      become: true
      shell: git clone https://git.mif.vu.lt/sest8864/web.git /usr/games/web

    - name: 12. Copy data from remote-med.sql to MySQL database
      become: true
      shell: mysql -u root -p{{ mysql_root_password }} -D {{ mysql_db_name }} < {{ sql_file_path }}

    - name: 13. Set bind-address in mysqld.cnf
      become: true
      lineinfile:
        path: "/etc/mysql/mysql.conf.d/mysqld.cnf"
        line: "bind-address = {{ mysql_bind_address }}"
      notify:
        - restart mysql service
        
    - name: 14. Install php-mbstring
      become: true
      apt: name=php-mbstring state=present    

  handlers:
    - name: restart mysql service
      become: true
      service:
        name: mysql
        state: restarted